#!/bin/bash

dcPrefix=/data/dc/dcall_null.
logPath="/tmp/logstash/hourly"

if [ ! -d "$logPath" ]; then
  mkdir -p "$logPath"
fi

last_hour=$(date -d '1 hour ago' "+%Y-%m-%d_%H")
cthour=$(date -d '1 hour ago' "+%Y%m%d%H")
cur_hour=$(date -d '0 hour ago' "+%Y-%m-%d_%H")
DATE=$(date -d "1 hour ago" +%Y-%m-%d)

HOST=$(hostname)

DCTS=(110002 110007 110008)

pjson=""
for DCT in ${DCTS[@]}
  do
  las_cnt=`grep "dcType\":\"$DCT" $dcPrefix"$last_hour"*|grep "createDt\":\"$cthour" |wc -l`
  cur_cnt=`grep "dcType\":\"$DCT" $dcPrefix"$cur_hour"*|grep "createDt\":\"$cthour"|wc -l`
  echo ${DCT} $cthour  $cur_cnt  $las_cnt >> $logPath/date_hours_$DATE
  # echo ${DCT} $cthour  $cur_cnt  $las_cnt
  pjson=$pjson@${DCT}_$[$las_cnt+$cur_cnt]
done
echo $pjson
curl -m 30 -o /dev/null -s -w %{http_code} "http://10.135.20.62:8888/hourly-flume_"$cthour"_$HOST?dt=$pjson"
# TODO
# curl -XPOST 10.135.20.62:8888/hours_flume_"$DATE"_$HOST --data-binary @/home/java/tmp/hours/thomas$DATE
